---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"

bases:
- github.com/redhat-cop/gitops-catalog/kiali-operator/overlays/default